Fix characters equals trim
VLysak/utils pull request #13
Opened 2018-04-24 20:48 UTC by VLysak

2018-04-26 13:52 UTC, vkushni requested changes
please rebase branch to develop

2018-04-30 13:43 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +        return toString().equals(new String(value));
1

2018-04-30 13:43 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +        return toString().equals(value.toString());
1

2018-04-30 13:43 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +        return toString().equals(value.toString());
1

2018-04-30 13:43 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +        return toString().equals(value.toString());
1

2018-04-30 13:43 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +//    public StringUtil trim() {
111

2018-04-30 13:57 UTC, VLysak commented on src/main/java/org/util/string/StringUtil.java
> +        } else if (trim == Trim.LEADING) {
1

2018-04-30 18:13 UTC, vkushni approved these changes

2018-04-30 18:13 UTC, merged