added-test-methods-for-size-reverse
VLysak/utils pull request #17
Opened 2018-05-04 17:25 UTC by VLysak

2018-05-04 17:28 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testSplit() {
1

2018-05-04 17:28 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil abc = new StringUtil("");
abc

2018-05-04 17:29 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals(Arrays.toString(new StringUtil[]{}), Arrays.toString(actual));
11

2018-05-04 17:29 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil abc = new StringUtil("1");
abc

2018-05-04 17:40 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil stringUtil = new StringUtil("");
input

2018-05-04 17:46 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testSplit() {
fix method naming

2018-05-04 17:49 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil abc = new StringUtil("a@-");
study before and before class

2018-05-04 17:51 UTC, VLysak commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil[] actual = abc.split("");
array can have any size from 0 to infinity

2018-05-06 08:51 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testSplitReturnArrayWithCorrectSireReturnedArray() {
testSplitArrayHasCorrectSizeWhen....

2018-05-07 02:06 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public enum Palindrome {
test can be implemented without using this enum

2018-05-07 02:07 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertAll(() -> assertEquals("a", actual[0].toString()),
consider using 3 different asserts instead of bulk one

2018-05-07 02:08 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil input = new StringUtil("");
input -> stringUtil or out (object under test) or sut (system under test)

2018-05-07 02:13 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil[] expected = new StringUtil[]{new StringUtil("a@-"), new StringUtil("b@")};
compare elements not arrays

2018-05-07 02:13 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        int expected = 2;
this variable is redundant

2018-05-07 02:14 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +                () -> assertEquals("kvadrad", input.set(input.size() - 1, 'd').toString()),
instead of calculations you should explicitly set indexes, - use `5` instead of `size() - 2`

2018-05-08 08:21 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        StringUtil[] actual = stringUtil.split("");
ensure this methods works same way as string.split

2018-05-08 08:21 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals(Arrays.toString(expected), Arrays.toString(actual));
1

2018-05-08 08:21 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals("a@-", actual[0].toString());
equals ?

2018-05-08 08:22 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals("-", actual[2].toString());
why don't you checking the 3rd part and 4th ?

2018-05-08 08:22 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        int stringUtilSize = new StringUtil("").size();
stringUtilSize --> size / actual, i like better 2nd one

2018-05-08 08:23 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testAppendEmptyStringBufferData() {
1

2018-05-08 08:23 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testAppendStringBufferData() {
1

2018-05-08 08:24 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        char actual = stringUtil.character(stringUtil.size() - 1);
size -1 - you have to replace this with real value

2018-05-08 08:25 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals("", actual.toString());
string util equals ?

2018-05-08 08:25 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testReverseWhenInStringUtilOneElement() {
this test must be parameterized

2018-05-08 08:26 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +    public void testSetElementsInDifferentPlaces() {
3 different test cases in one

2018-05-09 10:01 UTC, vkushni requested changes
Fix mentioned issues

2018-05-10 08:50 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +
1

2018-05-10 08:50 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        assertEquals(argument, stringUtilArray.get(0).reverse().toString());
more SRP

2018-05-10 08:53 UTC, vkushni commented on src/test/java/org/util/string/StringUtilTest.java
> +        List<StringUtil> stringUtilArray = new ArrayList<>();
1

2018-05-11 17:40 UTC, closed without merging